# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/token_style',
                'doc_host': 'https://silvaac.github.io',
                'git_url': 'https://github.com/silvaac/token_style',
                'lib_path': 'token_style'},
  'syms': {'token_style.core': {'token_style.core.foo': ('core.html#foo', 'token_style/core.py')}}}
