# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/token_style',
                'doc_host': 'https://silvaac.github.io',
                'git_url': 'https://github.com/silvaac/token_style',
                'lib_path': 'token_style'},
  'syms': { 'token_style.coinbase': { 'token_style.coinbase.coinbase_price_history': ( 'coinbase.html#coinbase_price_history',
                                                                                       'token_style/coinbase.py'),
                                      'token_style.coinbase.coinbase_to_file': ( 'coinbase.html#coinbase_to_file',
                                                                                 'token_style/coinbase.py'),
                                      'token_style.coinbase.coinbase_tokens': ('coinbase.html#coinbase_tokens', 'token_style/coinbase.py'),
                                      'token_style.coinbase.coinbase_usd_tokens': ( 'coinbase.html#coinbase_usd_tokens',
                                                                                    'token_style/coinbase.py'),
                                      'token_style.coinbase.read_all_files': ('coinbase.html#read_all_files', 'token_style/coinbase.py'),
                                      'token_style.coinbase.retrieve_coinbase_price': ( 'coinbase.html#retrieve_coinbase_price',
                                                                                        'token_style/coinbase.py'),
                                      'token_style.coinbase.save_file': ('coinbase.html#save_file', 'token_style/coinbase.py')},
            'token_style.core': {'token_style.core.foo': ('core.html#foo', 'token_style/core.py')}}}
